name: MutualInformation
channels:
  - bioconda
  - conda-forge
  - https://levinthal:paradox@conda.rosettacommons.org
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.8
  - ampl-mp=3.1.0
  - anarci=2021.02.04
  - ansiwrap=0.8.4
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.7.0
  - asttokens=2.1.0
  - attr=2.5.1
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - binutils_impl_linux-64=2.39
  - biopython=1.79
  - black=22.6.0
  - bleach=5.0.1
  - bokeh=2.4.3
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2024.3.11
  - cairo=1.16.0
  - ceres-solver=2.1.0
  - certifi=2024.2.2
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.1
  - cminpack=1.3.8
  - coin-or-cbc=2.10.8
  - coin-or-cgl=0.60.6
  - coin-or-clp=1.17.7
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.6
  - coinbonmin=1.8.9
  - colorama=0.4.6
  - contourpy=1.0.6
  - cryptography=38.0.4
  - curl=7.87.0
  - cycler=0.11.0
  - cytoolz=0.12.2
  - dask=2023.4.1
  - dask-core=2023.4.1
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.6
  - distributed=2023.4.1
  - dlib-cpp=19.24
  - eigen=3.4.0
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.0.4
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2023.10.0
  - gcc_impl_linux-64=12.2.0
  - gettext=0.21.1
  - gflags=2.2.2
  - gfortran_impl_linux-64=12.2.0
  - glib=2.74.1
  - glib-tools=2.74.1
  - glog=0.6.0
  - glpk=5.0
  - gmp=6.2.1
  - graphite2=1.3.13
  - gsl=2.7
  - gst-plugins-base=1.21.1
  - gstreamer=1.21.1
  - gxx_impl_linux-64=12.2.0
  - harfbuzz=5.3.0
  - hdf5=1.14.0
  - heapdict=1.0.1
  - hmat-oss=1.8.1
  - hmmer=3.3.2
  - icu=70.1
  - idna=3.4
  - importlib-metadata=5.0.0
  - importlib_resources=5.10.0
  - iniconfig=1.1.1
  - ipopt=3.14.10
  - ipykernel=6.17.1
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - jack=1.9.21
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.17.0
  - jupyter=1.0.0
  - jupyter_client=7.4.6
  - jupyter_console=6.4.4
  - jupyter_core=5.0.0
  - jupyter_server=1.23.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.3
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - levenshtein=0.20.8
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.4
  - libclang13=15.0.4
  - libcups=2.3.3
  - libcurl=7.87.0
  - libdb=6.2.32
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libhwloc=2.8.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.4
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.38
  - libpq=14.5
  - libsanitizer=12.2.0
  - libsndfile=1.1.0
  - libsodium=1.0.18
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=12.2.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libtmglib=3.9.0
  - libtool=2.4.6
  - libudev1=252
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.10.3
  - libzlib=1.2.13
  - locket=1.0.0
  - make=4.3
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - matplotlib-venn=0.11.9
  - metis=5.1.0
  - mistune=2.0.4
  - mpc=1.3.1
  - mpfr=4.1.0
  - mpg123=1.30.2
  - msgpack-python=1.0.3
  - mumps-include=5.2.1
  - mumps-seq=5.2.1
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - nbclassic=0.4.8
  - nbclient=0.7.0
  - nbconvert=7.2.5
  - nbconvert-core=7.2.5
  - nbconvert-pandoc=7.2.5
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nlopt=2.7.1
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.32
  - nss=3.78
  - numpy=1.23.4
  - openjpeg=2.5.0
  - openpyxl=3.1.2
  - openssl=1.1.1w
  - openturns=1.20
  - packaging=21.3
  - pagmo=2.19.0
  - pandas=1.5.1
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - pango=1.50.12
  - papermill=2.3.4
  - parso=0.8.3
  - partd=1.4.1
  - pathspec=0.11.0
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - primesieve=8.0
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.32
  - prompt_toolkit=3.0.32
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=14.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.13.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.2
  - pysocks=1.7.1
  - pytest=7.2.0
  - python=3.11.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-igraph=0.10.4
  - python-levenshtein=0.20.8
  - python-lmdb=1.4.1
  - python-tzdata=2022.7
  - python_abi=3.11
  - pytz=2022.6
  - pytz-deprecation-shim=0.1.0.post0
  - pyyaml=6.0
  - pyzmq=24.0.1
  - qt-main=5.15.6
  - qtconsole=5.4.0
  - qtconsole-base=5.4.0
  - qtpy=2.3.0
  - r-base=4.2.2
  - rapidfuzz=2.13.2
  - readline=8.1.2
  - rpy2=3.5.10
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - scotch=6.0.9
  - seaborn=0.12.1
  - seaborn-base=0.12.1
  - sed=4.8
  - send2trash=1.8.0
  - setuptools=65.5.1
  - simplegeneric=0.8.1
  - sip=6.7.4
  - six=1.16.0
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlite=3.39.4
  - stack_data=0.6.1
  - statsmodels=0.13.5
  - suitesparse=5.10.1
  - sysroot_linux-64=2.12
  - tbb=2021.7.0
  - tbb-devel=2021.7.0
  - tblib=1.7.0
  - terminado=0.17.0
  - texttable=1.6.7
  - textwrap3=0.9.2
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.5.0
  - typed-ast=1.5.4
  - typing_extensions=4.4.0
  - tzdata=2022f
  - tzlocal=4.2
  - unixodbc=2.3.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - wheel=0.38.4
  - widgetsnbextension=4.0.3
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=3.0.0
  - zipp=3.10.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - coverage==7.3.0
      - imgtgenedl==0.5.2
      - julia==0.6.0
      - logomaker==0.8
      - pyrepseq==1.0
      - pytest-cov==4.1.0
      - requests==2.28.1
      - semantic-version==2.10.0
      - stitchr==1.1.2
      - tenacity==8.1.0
      - tidytcells==1.6.0
      - urllib3==1.26.13
